language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CRFEntityExtractor
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DIETClassifier 
  - name: FallbackClassifier


policies:
  - name: TEDPolicy
    max_history: 20
    epochs: 20
